apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
omitStages:
  - "ResponseStarted"
  - "RequestReceived"
rules:

  # Don't log system requests.
  - level: None
    userGroups: ["system:serviceaccounts:hypercloud4-system", "system:nodes", "system:serviceaccounts", "system:masters"]
    
  # Don't log requests by hypercloud4-admin and kube-system user.
  - level: None
    users: ["system:serviceaccount:hypercloud4-system:hypercloud4-admin", "system:kube-controller-manager", "system:kube-scheduler", "system:apiserver"]
    
  # Don't log watch and get request
  - level: None
    verbs: ["watch", "get", "list"]
  
  # Log the response body of pod changes.
  - level: RequestResponse
    verbs: ["create", "delete"]
    resources:
    - group: ""
      resources: ["pods"]
      
  # Log the request body of configmap changes in kube-system.
  - level: Metadata
    resources:
    - group: ""
    - group: "admissionregistration.k8s.io"
    - group: "apiextensions.k8s.io"
    - group: "apiregistration.k8s.io"
    - group: "apps"
    - group: "authentication.istio.io"
    - group: "autoscaling"
    - group: "batch"
    - group: "cdi.kubevirt.io"
    - group: "ceph.rook.io"
    - group: "cluster.x-k8s.io"
    - group: "config.istio.io"
    - group: "core.kubefed.io"
    - group: "extensions"
    - group: "kubevirt.io"
    - group: "networking.istio.io"
    - group: "policy"
    - group: "rbac.authorization.k8s.io"
    - group: "rbac.istio.io"
    - group: "security.istio.io"
    - group: "servicecatalog.k8s.io"
    - group: "storage.k8s.io"
    - group: "tekton.dev"
    - group: "tmax.io"
    - group: "types.kubefed.io"
  
  # Don't log others.
  - level: None
