apiVersion: hyperflow.tmax.io/v1
kind: Notebook
metadata:
  labels:
    app: demo-notebook
  name: demo-notebook
  namespace: demo
spec:
  template:
    spec:
      containers:
        - env:
            ## 폐쇄망 registry 주소 (수정 필요)
          - name: REGISTRY
            value: "192.168.6.181:5000"
          ## notebook image 정의 (수정 필요)
          image: '192.168.6.181:5000/tmaxcloudck/kubeflow-jupyter-lab:v0.1'
          name: demo
          resources:
            ## notebook 사양 정의
            requests:
              cpu: "0.5"
              memory: 1.0Gi
          volumeMounts:
            - mountPath: /home/jovyan
              name: demo-pvc
            - mountPath: /dev/shm
              name: dshm
      serviceAccountName: default-editor
      ttlSecondsAfterFinished: 300
      ## 사용할 volume 정의
      volumes:
        - name: demo-pvc
          persistentVolumeClaim:
            claimName: demo-pvc
        - emptyDir:
            medium: Memory
          name: dshm
  ## 사용할 volumeClaim 정의 : 없으면 새로 pvc를 생성
  volumeClaim:
    - name: demo-pvc
      size: 10Gi